const products = [
    {
        id: 1,
        category: "shirt",
        type: "cartoon",
        name: "Princess Gum Gift",
        search: "وقت المغامرة Adventure Time Marceline Bubblegum Rock مارسيلين هدية أميرة العلكة اميرة العلكة gift",
        desc: "تيشرت مستوحى من هدية مارسلين لأميرة العلكة في Adventure Time، بتصميم مرح وجريء.",
        price: 3200,
        promo: 3800,
        img: ["../public/assets/image/1/1.png","../public/assets/image/1/1.jpeg","../public/assets/image/1/1.jpg"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 2,
        category: "shirt",
        type: "anime",
        name: "Uchiha Clan Sharingan",
        search: "naruto ناروتو itachi sasuke أوتشيهااوتشيها ساسكي ايتاتشي إيتاتشي مادارا madara الشارينغان",
        desc: "بتصميم يجمع بين شخصيات تمتلك الشارينغان ويبرز تفاصيله بلون أحمر جريء على خلفية سوداء, خيار رائع لعشاق الأنمي والطابع القوي.",
        price: 3400,
        promo: 4000,
        img: ["../public/assets/image/2/2.png","../public/assets/image/2/2.jpg","../public/assets/image/2/2-1.jpg"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 3,
        category: "shirt",
        type: "anime",
        name: "War Is Over Shanks",
        search: "One Piece Warrior Spirit شانكس ون بيس",
        desc:"تيشرت بستايل أنمي يجسد شينكس بتصميم جريء مستوحى من أنمي One Piece، مثالي لعشاق ون بيس والموضة المميزة.",
        price: 2700,
        img: ["../public/assets/image/3/3-1.png","../public/assets/image/3/3.png"],
        colors: ["white" ,"black","#2c523a"],
        sizes: ["S", "M", "L","XL","XXL"],
    }
    ,
    {
        id: 4,
        category: "shirt",
        type: "design",
        name: "Enticing",
        search: "Girl فتيات Girls فتاة بنت بنات",
        desc: "تيشرت عصري بتصميم ملفت يجمع بين الفن الياباني والأسلوب الحديث، يتميز برسم لشخصية موشومة مع خلفية فنية ونصوص إنجليزية ويابانية.",
        price: 3000,
        promo: 3600,
        img:["../public/assets/image/4/4.png","../public/assets/image/4/4-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 5,
        category: "shirt",
        type: "anime",
        name: "Son Goku",
        search: "Dragon Ball دراغون بول سون غوكو",
        desc: "تيشرت أنيق بتصميم مستوحى من شخصية سون غوكو في Dragon Ball, يتميز بطباعة جريئة تضم صورًا متعددة لغوكو، مع نصوص باليابانية والإنجليزية لإضفاء لمسة فريدة.",
        price: 3200,
        promo: 3800,
        img:["../public/assets/image/5/5.png","../public/assets/image/5/5-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 6,
        category: "shirt",
        type: "anime",
        search: "فوشيغورو توجي Jujutsu Kaisen جوجوتسو كايسن",
        name: "Fushiguro Toji",
        desc: "تيشرت بتصميم مستوحى من شخصية فوشيغورو توجي من Jujutsu Kaisen، يتميز بخلفية الدائرة الحمراء التي تضفي عليه طابعًا قويًا وجذابًا.",
        price: 2900,
        img:["../public/assets/image/6/6.png","../public/assets/image/6/6-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 7,
        category: "shirt",
        type: "design",
        search: "girl فتاة فتيات بنات بنت Tokyo طوكيو",
        name: "Tokyo",
        desc: "تيشرت أنيق يحمل تصميمًا مستوحى من طوكيو بطابع غامض ومميز. يتميز بثلاثة لوحات فنية لعيون بتفاصيل دقيقة، مع نصوص باليابانية والإنجليزية تعزز جاذبيته الفريدة.",
        price: 2900,
        promo: 3800,
        img:["../public/assets/image/7/7.png","../public/assets/image/7/7-1.jpg","../public/assets/image/7/7-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L"],
    },
    {
        id: 8,
        category: "shirt",
        type: "anime",
        search: "hunter x hunter zoldyck zoldik القناص كيلوا زولديك",
        name: "Killua Vibe",
        desc: "تيشرت أنيق مستوحى من شخصية كيلوا زولديك من أنمي Hunter x Hunter, يتميز بتصميم أبيض وأسود يجسد كيلوا وهو يشرب من كوب.",
        price: 3200,
        promo: 4000,
        img:["../public/assets/image/8/8.png","../public/assets/image/8/8-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L","XL"],
    },
    {
        id: 9,
        category: "shirt",
        type: "anime",
        name: "Tokyo Ghoul",
        search: "كانيكي طوكيو غول kaneki",
        desc: "بتصميم يجسد كانيكي كن من Tokyo Ghoul بلمسة فنية جريئة. يتميز بالخلفية السوداء والتفاصيل الحمراء التي تعكس طابع الأنمي المميز.",
        price: 2900,
        promo: 3500,
        img: ["../public/assets/image/9/9.png","../public/assets/image/9/9-1.png"],
        colors: ["white" ,"black"],
        sizes: ["S", "M", "L", "XL"],
    },
]

export default products;